### ISSUE TITLE
Enter should close an open directory in tree view

### ISSUE THREAD

**Issue by nunull** [marssaxman/ozette#24]
In tree view, you are able to expand directories using the enter key. I think it would feel more natural if you could also do vice versa.

**Comment by marssaxman** [comment]
My thinking was that the space bar would toggle open/closed, while the enter key would drill in by using the selected directory as the typeahead filter prefix. I will mess with it and see if I can come up with a heuristic to make it work both ways.

**Comment by nunull** [comment]
Allright, that wasn't really clear to me, but sounds like a good idea. Maybe it would be a good idea to clarify this (visually).
