### ISSUE TITLE
(OSX) Control-Left-Arrow and Control-Right-Arrow don't work

### ISSUE THREAD

**Issue by nunull** [marssaxman/ozette#25]
For me control-left and control-right-arrow keys don't work on OSX. This is because they are supposed to switch between desktops by default.

Is there any plan for implementing some kind of configuration for keybindings or providing some alternative for switching tabs?

**Comment by marssaxman** [comment]
I'm surprised to hear it - I have not encountered this on OS X. What do you mean by "switch between desktops"? Which version of OS X are you using?

I prefer to keep configuration options to a minimum, as a rule, but perhaps this one is unavoidable. What keys might you like to use?

**Comment by marssaxman** [comment]
Aha, just had a look through "System Preferences" and I see that the "Mission Control" system uses these keystrokes. Never used it myself, but I can see why the conflict is a problem.

**Comment by marssaxman** [comment]
Would an alt-tab like mechanism solve this, perhaps? Control-tilde to bring up a list of open tabs, using the same design as the directory picker dialog, so you can type a number to pick the tab you want to view?

**Comment by nunull** [comment]
I personally really like Alt+Tab. It would be interesting to hear what preferences others have, though.

**Comment by marssaxman** [comment]
We can't use alt-tab itself because the OS handles it, but it seems like a good backup navigation model.

**Comment by marssaxman** [comment]
Alt-Left-Arrow and Alt-Right-Arrow can be used in place of Control-Left-Arrow and Control-Right-Arrow if the latter are for some reason unavailable.
