### ISSUE TITLE
Pressing "Ctrl-e" inside the help browser results in segfault.

### ISSUE THREAD

**Issue by skx** [marssaxman/ozette#26]
Open `ozette` and press:

1. `ctrl-?`, such that the help page opens.
2. `ctrl-e`, such that you could enter a shell  command. 

Instead of the shell-command the editr segfaults.

**Comment by marssaxman** [comment]
That is weird.

**Comment by skx** [comment]
Can you confirm, or should I give you a backtrace from the crash?

**Comment by marssaxman** [comment]
It crashes for me as well. If you have a backtrace handy I'd love to see it, just to make sure it's crashing in the same way for both of us.

**Comment by skx** [comment]
Sorry for the slow reply, this is the backtrace I see:

      (gdb) bt
      #0  check_halt_node_context (context=<optimized out>, node=<optimized out>, dfa=<optimized out>)    at regexec.c:1217
      #1  check_halt_state_context (mctx=<optimized out>, state=<optimized out>, idx=<optimized out>)    at regexec.c:1243
      #2  0x00007f39b65ac662 in check_matching (p_match_first=0x7fffbf94552c,     fl_longest_match=<optimized out>, mctx=<optimized out>) at regexec.c:1190
      #3  re_search_internal (preg=<optimized out>, string=<optimized out>, length=<optimized out>,     start=<optimized out>, range=<optimized out>, stop=<optimized out>, nmatch=<optimized out>,     pmatch=0x7fffbf945610, eflags=0) at regexec.c:829
      #4  0x00007f39b65ad473 in __regexec (preg=0x25e76c0,     string=0x25cccc8 "Ozette is an editing shell for software development. It combines a directory", nmatch=1, pmatch=0x7fffbf945610, eflags=<optimized out>) at regexec.c:253
      #5  0x000000000042539b in Syntax::Regex::find (this=0x25e76c0, text=..., offset=0)    at ./src/app/syntax.cpp:40
      #6  0x00000000004258b8 in Syntax::Grammar::parse (this=0x25e7678, text=...)    at ./src/app/syntax.cpp:94
      #7  0x00000000004265a6 in Editor::DisplayLine::DisplayLine (this=0x7fffbf945830, text=...,     settings=..., syntax=...) at ./src/editor/displayline.cpp:34
      #8  0x0000000000434a2f in Editor::Document::display (this=0x25e7670, index=1)    at ./src/editor/document.cpp:167
      #9  0x000000000041fb62 in Editor::View::paint_line (this=0x25e7650, dest=0x25b7af0, v=1,     state=UI::View::Inactive) at ./src/editor/editor.cpp:184
      #10 0x000000000041ea23 in Editor::View::paint_into (this=0x25e7650, dest=0x25b7af0,     state=UI::View::Inactive) at ./src/editor/editor.cpp:77
      #11 0x0000000000429382 in UI::View::paint (this=0x25e7650, state=UI::View::Inactive)    at ./src/ui/view.cpp:61
      #12 0x00000000004327fb in UI::Window::paint_content (this=0x25cfb50) at ./src/ui/window.cpp:273
      #13 0x000000000043272c in UI::Window::paint (this=0x25cfb50) at ./src/ui/window.cpp:261
      #14 0x0000000000431fdc in UI::Window::clear_focus (this=0x25cfb50) at ./src/ui/window.cpp:109
      #15 0x000000000042b609 in UI::Shell::set_focus (this=0x2586048, index=0) at ./src/ui/shell.cpp:180
      #16 0x000000000042b4d1 in UI::Shell::make_active (this=0x2586048, window=0x25b7c30)  at ./src/ui/shell.cpp:162
      #17 0x00000000004179e9 in Browser::View::open (path=..., shell=...) at ./src/browser/browser.cpp:39
      #18 0x000000000040deea in Ozette::show_browser (this=0x2586040) at ./src/app/ozette.cpp:195
      #19 0x000000000040f196 in Ozette::execute (this=0x2586040) at ./src/app/ozette.cpp:288
      #20 0x000000000040de45 in Ozette::run (this=0x2586040) at ./src/app/ozette.cpp:186
      #21 0x000000000042abd0 in main (argc=1, argv=0x7fffbf945ca8) at ./src/main.cpp:40
      (gdb) 

I hope that was slightly useful.  (Confirmed as still being an issue with the current git repo.)

**Comment by marssaxman** [comment]
Thank you - that is the same crash I'm seeing. Bit of a puzzler: the regex engine is choking, but only when it's processing non-editable text in a window that has just been deactivated.
