### ISSUE TITLE
Fails to compile, need to include <functional>.

### ISSUE THREAD

**Issue by leetNightshade** [marssaxman/ozette#35]
You don't have precompiled headers setup for your project, and any place that uses std::function fails to compile for me on Arch with gcc 8.1.1. You need to make sure to include <functional> in any place that uses it.

**Comment by marssaxman** [comment]
Thanks for the catch! I wonder why I'm not getting errors when I build on Ubuntu 16.04, and whether there's some way I can convince the compiler to be more strict about it.
